import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StaggeredMenuWrapper from "@/components/ui/StaggeredMenuWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StaggeredMenuWrapper />
        <div
          style={{
              height: "100vh",
              overflow: "auto",
              background: `linear-gradient(to bottom right, #d9f99d 10%, #ecfccb 20%, #fff 70%)`,
              paddingTop: "100px",
          }}>
          {children}
        </div>
      </body>
    </html>
  );
}
